config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:index, :show] do
    resources :reviews, only: [:index, :new, :create]
  end


  resources :reviews, only: :index

  namespace :admin do
    resources :books, only: [:index, :edit, :update, :new, :create]
  end
end

app/models/Book.rb
class Book < ApplicationRecord
  has_many :reviews
end

app/models/Review.rb
class Review < ApplicationRecord
  belongs_to :book
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.new(books_params)
    if book.save
      redirect_to admin_books_path
    else
      render 'new'
    end

  end

  def books_params
    params.require(:book).permit(:title, :author, :year)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    if params[:book_id].nil?
      @reviews = Review.all
    else
      @reviews = Review.where("book_id = ?", params[:book_id])
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/edit.html.erb
<h2>A tale of two cities</h2>
<p>Charles Dickens</p>
<p>1903</p>
<button type='button'>Update</button>
<button type='button'>Delete</button>

app/views/admin/books/index.html.erb
<h1>Books</h1>

<% @books.each do |b| %>
  <div>
    <%= link_to b.title, edit_admin_book_path(b) %>
    <p><%= b.author %></p>
    <p><%= b.year %></p>
  </div>
<% end %>

<button type="button" name="add-book">Add a new book</button>

app/views/admin/books/new.html.erb
<%= form_for([:admin, @book]) do |f|%>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :author %>:
  <%= f.text_field :author %><br />

  <%= f.label :year %>:
  <%= f.text_field :year %><br />

  <%= f.submit "Create Book" %>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>

<%= render "shared/book" %>

app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<p>
  <%= @book.author %>
</p>
<p>
  <%= @book.year %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookstoreTdd</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<ul>
  <li>Great book</li>
  <li>Rubbish book</li>
</ul>

<ul>
  <% @reviews.each do |r| %>
    <li>
      <p>
        <%= r.book.title %>
      </p>
      <%= r.comment %>
    </li>
  <% end %>
</ul>

app/views/shared/_book.html.erb
<% @books.each do |b| %>
  <div>
    <p>
      <%= b.title %>
    </p>
    <p><%= b.author %></p>
    <p><%= b.year %></p>
  </div>
<% end %>